name: Terraform Lint

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~> 1.6"

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Init (no backend)
        working-directory: terraform
        run: terraform init -backend=false

      - name: Format check
        run: terraform fmt -check -recursive

      - name: Validate
        working-directory: terraform
        run: terraform validate

      - name: TFLint
        working-directory: terraform
        run: tflint -f compact
